// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoPgdr7yLuVMBnWf4u3VB-A9071hglFc8',
    appId: '1:998012965470:web:0c7cd7f13704f9a6c65acf',
    messagingSenderId: '998012965470',
    projectId: 'operaapp-45b6d',
    authDomain: 'operaapp-45b6d.firebaseapp.com',
    storageBucket: 'operaapp-45b6d.appspot.com',
    measurementId: 'G-N65BYLL5KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBxRJLXLPDe6MExq-3UhYSGzfghsyshKY',
    appId: '1:998012965470:android:4055c91cb6ca2c8ec65acf',
    messagingSenderId: '998012965470',
    projectId: 'operaapp-45b6d',
    storageBucket: 'operaapp-45b6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYiIUnWadTPJbwO6c2ANW5Cv5oWlHtSgY',
    appId: '1:998012965470:ios:380c36989563698fc65acf',
    messagingSenderId: '998012965470',
    projectId: 'operaapp-45b6d',
    storageBucket: 'operaapp-45b6d.appspot.com',
    iosClientId: '998012965470-f6jjm6a8rqnvv02f64a9vutpt21an602.apps.googleusercontent.com',
    iosBundleId: 'com.example.operaAppWindows',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYiIUnWadTPJbwO6c2ANW5Cv5oWlHtSgY',
    appId: '1:998012965470:ios:41d6992ea9977033c65acf',
    messagingSenderId: '998012965470',
    projectId: 'operaapp-45b6d',
    storageBucket: 'operaapp-45b6d.appspot.com',
    iosClientId: '998012965470-t31l96h2ntfppcqh5gqtfphm2ol0pmrp.apps.googleusercontent.com',
    iosBundleId: 'com.example.operaAppWindows.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoPgdr7yLuVMBnWf4u3VB-A9071hglFc8',
    appId: '1:998012965470:web:264dd5d3800e22e6c65acf',
    messagingSenderId: '998012965470',
    projectId: 'operaapp-45b6d',
    authDomain: 'operaapp-45b6d.firebaseapp.com',
    storageBucket: 'operaapp-45b6d.appspot.com',
    measurementId: 'G-ZSVJ15XSJW',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyBoPgdr7yLuVMBnWf4u3VB-A9071hglFc8',
    appId: '1:998012965470:web:90b112088878d4f1c65acf',
    messagingSenderId: '998012965470',
    projectId: 'operaapp-45b6d',
    authDomain: 'operaapp-45b6d.firebaseapp.com',
    storageBucket: 'operaapp-45b6d.appspot.com',
    measurementId: 'G-T4737E43T7',
  );
}
